# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-04-30 16:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classifieds', '0004_massage_read'),
    ]

    operations = [
        migrations.AlterField(
            model_name='massage',
            name='receiver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
