# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-05-02 17:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifieds', '0005_auto_20180430_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='posting',
            name='airport',
            field=models.CharField(blank=True, max_length=3),
        ),
    ]
