# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-05-03 18:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifieds', '0007_auto_20180502_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum_post',
            name='sticky',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='forum_topic',
            name='catregory',
            field=models.CharField(choices=[('Delay Info', 'Delay Info'), ('Things to do in the Area', 'Things to do in the Area'), ('Airport Tips/Hacks', 'Airport Tips/Hacks'), ('NTR', 'NTR')], default='NTR', max_length=50),
            preserve_default=False,
        ),
    ]
