# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-05-15 18:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifieds', '0008_auto_20180503_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='posting',
            name='cost',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
