# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-05-15 19:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifieds', '0011_auto_20180515_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posting',
            name='header',
            field=models.CharField(blank=True, max_length=35),
        ),
    ]
